import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    environment: 'jsdom',
    include: ['src/**/*.spec.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: 'coverage',
      include: [
        'src/components/admin/AdminUserCard.vue',
        'src/components/admin/AdminOrganizerRequestsPanel.vue',
        'src/components/admin/AdminServicesPanel.vue',
        'src/components/admin/AdminTracksPanel.vue',
        'src/components/admin/AdminUsersPanel.vue',
        'src/components/AppHeader.vue',
        'src/components/AppFooter.vue',
        'src/components/AppModal.vue',
        'src/components/AppToast.vue',
        'src/components/AuthDialog.vue',
        'src/components/auth/AuthAccessPanel.vue',
        'src/components/auth/AuthSessionPanel.vue',
        'src/components/CatalogPage.vue',
        'src/components/ContentSection.vue',
        'src/components/DetailInfoCard.vue',
        'src/components/EventBookingDialog.vue',
        'src/components/EventCard.vue',
        'src/components/EventAttendeeList.vue',
        'src/components/EventAvailabilityBadge.vue',
        'src/components/EventSearchToolbar.vue',
        'src/components/event-detail/EventBookingSummaryCard.vue',
        'src/components/event-detail/EventDetailCircuitOverview.vue',
        'src/components/event-detail/EventDetailHero.vue',
        'src/components/event-detail/EventServiceConfigurator.vue',
        'src/components/HeroInfoPanel.vue',
        'src/components/messages/MessageComposePanel.vue',
        'src/components/messages/MessageConversationPanel.vue',
        'src/components/messages/MessageThreadSidebar.vue',
        'src/components/MetricCard.vue',
        'src/components/organizer/OrganizerEventsPanel.vue',
        'src/components/organizer/OrganizerServicesPanel.vue',
        'src/components/organizer/OrganizerStatsPanel.vue',
        'src/components/PageHero.vue',
        'src/components/profile/ProfileBookingDetailDialog.vue',
        'src/components/profile/ProfileBookingsPanel.vue',
        'src/components/profile/ProfileLapTimesPanel.vue',
        'src/components/profile/OrganizerAccountDetailsPanel.vue',
        'src/components/profile/UserAccountDetailsPanel.vue',
        'src/components/RankingPositionBadge.vue',
        'src/components/SectionCard.vue',
        'src/components/TrackCard.vue',
        'src/components/TrackRecordBoard.vue',
        'src/components/UserProfileHero.vue',
        'src/components/UserProfileLink.vue',
        'src/composables/useMessageInbox.ts',
        'src/composables/useToast.ts',
        'src/utils/apiErrors.ts',
        'src/utils/authRoles.ts',
        'src/utils/date.ts',
        'src/utils/eventAvailability.ts',
        'src/utils/format.ts',
        'src/utils/identity.ts',
        'src/utils/messageFormatting.ts',
        'src/utils/messageThreads.ts',
        'src/utils/trackMedia.ts',
        'src/utils/visualPalettes.ts',
      ],
      exclude: [
        'src/main.ts',
        'src/router/**',
        'src/types/**',
        'src/assets/**',
        'src/**/__tests__/**',
      ],
    },
  },
})
