spring.application.name=backend
spring.datasource.url=jdbc:mariadb://localhost:3306/trackfinder
spring.datasource.username=trackuser
spring.datasource.password=trackpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false